const MOVE_PLAYER = "MOVE_PLAYER";
const BUILD_WALL = "BUILD_WALL";
const SHOOT_PROJECTILE = "SHOOT_PROJECTILE";
const UPDATE_PROJECTILES = "UPDATE_PROJECTILES";
const ROTATE_PLAYER = "ROTATE_PLAYER";
const DAMAGE_WALL = "DAMAGE_WALL";
const RERENDER = "RERENDER";
const START_GAME = "START_GAME";

export {MOVE_PLAYER, BUILD_WALL, SHOOT_PROJECTILE, UPDATE_PROJECTILES, ROTATE_PLAYER, DAMAGE_WALL, RERENDER, START_GAME};