const BUILD_WALL = "BUILD_WALL";
const DAMAGE_WALL = "DAMAGE_WALL";
const MOVE_PLAYER = "MOVE_PLAYER";
const PAUSE_GAME = "PAUSE_GAME"
const RERENDER = "RERENDER";
const ROTATE_PLAYER = "ROTATE_PLAYER";
const SHOOT_PROJECTILE = "SHOOT_PROJECTILE";
const SPECTATE = "SPECTATE";
const START_GAME = "START_GAME";
const UNPAUSE_GAME = "UNPAUSE_GAME"
const UPDATE_PROJECTILES = "UPDATE_PROJECTILES";

export {MOVE_PLAYER, BUILD_WALL, SHOOT_PROJECTILE, UPDATE_PROJECTILES, ROTATE_PLAYER, DAMAGE_WALL, UNPAUSE_GAME, RERENDER, PAUSE_GAME, SPECTATE, START_GAME};